version: '3.9'

services:
  tinamys-26022024:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinamys26022024
    ports:
      - '3001:3000'
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=tinamys26022024
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
